/**
 * Config resource types.
 *
 * These types represent the domain model for config resources after
 * unwrapping the JSON:API envelope.
 */

/** A config resource as returned by the smplkit Config API. */
export interface Config {
  /** UUID of the config. */
  id: string;

  /** Human-readable key (e.g. `"user_service"`). */
  key: string;

  /** Display name for the config. */
  name: string;

  /** Optional description. */
  description: string | null;

  /** Parent config UUID, or null if this is a root config. */
  parent: string | null;

  /** Base key-value pairs. */
  values: Record<string, unknown>;

  /** Per-environment overrides, keyed by environment name. */
  environments: Record<string, Record<string, unknown>>;

  /** When the config was created, or null if unavailable. */
  createdAt: Date | null;

  /** When the config was last updated, or null if unavailable. */
  updatedAt: Date | null;
}

/** Options for creating a new config. */
export interface CreateConfigOptions {
  /** Display name for the config. */
  name: string;

  /** Human-readable key. Auto-generated by the server if omitted. */
  key?: string;

  /** Optional description. */
  description?: string;

  /** Parent config UUID. */
  parent?: string;

  /** Initial base values. */
  values?: Record<string, unknown>;
}

/** Options for fetching a single config. Exactly one of `key` or `id` must be provided. */
export interface GetConfigOptions {
  /** Fetch by human-readable key. */
  key?: string;

  /** Fetch by UUID. */
  id?: string;
}
